### ISSUE TITLE
How to (poly)fill out customPeerConnectionWithRtpSender() ?

### ISSUE THREAD

**Issue by steely-glint** [w3c/webrtc-rtptransport#69]
The explainer-use-case-1 handwaves on how an RTP peerconnecton gets created.
I've been trying to coerce the existing APIs to

- Create an SDP offer that only contains what I intend to send
- Actually send packets with the correct ptype that matches that SDP
- without using a mediastream track as a dummy (ideally)

So far I've failed (using the interfaces currently in chrome canary).
Is it possible (without resorting to local description SDP mangling)?
If not, what's the minimal set of APIs that would let me create an offer that is send-only H264 and then send packets in that.

**Comment by alvestrand** [comment]
In theory, I think you should be able to generate the SDP with:
- pc = new RTCPeerConnection()
- pc.addTransceiver('video')
- pc.setCodecPreferences(h264)
- pc.createOffer()
For sending the packet, I think you need the EncodedSource API that @guidou is defining, due to the limitation that you can't send new packets in the EncodedTransform API.

**Comment by steely-glint** [comment]
Thanks. 
Current WIP is here:
https://pipe.github.io/echoRtp/
It seems to work - except that NACK and PLI are missing.
